/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppComputerCard: typeof import('./src/components/AppComputerCard.vue')['default']
    AppInfoBox: typeof import('./src/components/AppInfoBox.vue')['default']
    Asdasd: typeof import('./src/components/asdasd.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Chart: typeof import('primevue/chart')['default']
    Chip: typeof import('primevue/chip')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Drawer: typeof import('primevue/drawer')['default']
    HelpGuide: typeof import('./src/components/HelpGuide.vue')['default']
    HelpSupport: typeof import('./src/components/HelpSupport.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    Image: typeof import('primevue/image')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Knob: typeof import('primevue/knob')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Rating: typeof import('primevue/rating')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skeleton: typeof import('primevue/skeleton')['default']
    StatsAssets: typeof import('./src/components/StatsAssets.vue')['default']
    StatsProducts: typeof import('./src/components/StatsProducts.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheNavbar: typeof import('./src/components/TheNavbar.vue')['default']
    VesselsSkeleton: typeof import('./src/components/VesselsSkeleton.vue')['default']
    VesselsTable: typeof import('./src/components/VesselsTable.vue')['default']
    VesselsTableExpansion: typeof import('./src/components/VesselsTableExpansion.vue')['default']
    VesselsTableHeader: typeof import('./src/components/VesselsTableHeader.vue')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
